CREATE TABLE IF NOT EXISTS TY_PROJECT_DESIGN
(
    ID                      VARCHAR(200)  NOT NULL PRIMARY KEY COMMENT '主键ID',
    NAME                    VARCHAR(200)  NOT NULL COMMENT '名称',
    REMARK                  VARCHAR(200)  NULL COMMENT '备注',
    CREATE_BY               VARCHAR(200)  NOT NULL COMMENT '创建人',
    CREATE_DATE_TIME        DATETIME      NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_BY        VARCHAR(200)  NOT NULL COMMENT '修改人',
    LAST_MODIFIED_DATE_TIME DATETIME      NOT NULL COMMENT '修改时间',
    DELETED                 INT DEFAULT 0 NOT NULL COMMENT '逻辑删除',
    VERSION_NUMBER          BIGINT        NOT NULL COMMENT '版本号',
    TENANT_ID               VARCHAR(200)  NULL COMMENT '租户ID'
) COMMENT='项目设计表';

ALTER TABLE TY_PROJECT_DESIGN ADD COLUMN PROJECT_ID VARCHAR(200) NULL COMMENT '项目ID';
