CREATE TABLE IF NOT EXISTS TY_PROJECT_DESIGN
(
    ID                      VARCHAR(200)  NOT NULL PRIMARY KEY,
    NAME                    VARCHAR(200)  NOT NULL,
    REMARK                  VARCHAR(200),
    CREATE_BY               VARCHAR(200)  NOT NULL,
    CREATE_DATE_TIME        TIMESTAMP     NOT NULL,
    LAST_MODIFIED_BY        VARCHAR(200)  NOT NULL,
    LAST_MODIFIED_DATE_TIME TIMESTAMP     NOT NULL,
    DELETED                 INT DEFAULT 0 NOT NULL,
    VERSION_NUMBER          BIGINT        NOT NULL,
    TENANT_ID               VARCHAR(200)
);

ALTER TABLE TY_PROJECT_DESIGN ADD COLUMN IF NOT EXISTS PROJECT_ID VARCHAR(200);
